name: "Cover Art Archive"
guid: "8119f3c6-cfc2-4d9c-a0ba-028f1d93e526"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-coverartarchive.png"
version: "4"
targetAbi: "10.8.0.0"
framework: "net6.0"
overview: "MusicBrainz Cover Art Archive"
description: >
  This plugin provides images from the Cover Art Archive https://musicbrainz.org/doc/Cover_Art_Archive and depends on the MusicBrainz metadata provider to know what images belong where

category: "Metadata"
owner: "jellyfin"
artifacts:
  - "Jellyfin.Plugin.CoverArtArchive.dll"
changelog: |2-
  ### Code or Repo Maintenance ###
  - 10.8 support (#13) @crobibero
